version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: trip_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trip_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trips-net

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - trips-net

  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    networks:
      - trips-net

volumes:
  mysql_data:

networks:
  trips-net:
    driver: bridge
