version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: trip_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trip_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
